#!/bin/sh

# If deploy/azuredeploy.bicep is staged then run
# az bicep build -f azuredeploy.bicep against it
git diff --cached --name-status | awk '$1 != "D" { print $2 }' | grep -qFx 'deploy/azuredeploy.bicep'
if [ $? -eq 0 ]; then
	echo 'Compiling bicep into arm'
	# Only compile staged changes
	git show ":deploy/azuredeploy.bicep" > /tmp/azuredeploy.bicep
	az bicep build -f /tmp/azuredeploy.bicep --outdir deploy
	git add deploy/azuredeploy.json
fi

git diff --cached --name-status | awk '$1 != "D" { print $2 }' | grep -qFx 'deploy/e2e-durable/azuredeploy.bicep'
if [ $? -eq 0 ]; then
	echo 'Compiling durable e2e bicep into arm'
	# Only compile staged changes
	git show ":deploy/e2e-durable/azuredeploy.bicep" > /tmp/azuredeploy.bicep
	az bicep build -f /tmp/azuredeploy.bicep --outdir deploy/e2e-durable
	git add deploy/e2e-durable/azuredeploy.json
fi

# Format files with dotnet-format
dotnet format src/GoogleFitOnFhir.sln -wsa