parameters:
  environment: ''

stages:
  - stage: Build
    displayName: Building
    dependsOn: []
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: BuildPlaceholder       # Rename to Build<Project>
        displayName: Build Project  # Having 1 job per build means
        steps:                      # they run in parallel
          - bash: echo "🔨👷"
            displayName: Build the Bob
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: '**/*.csproj'
