parameters:
  environment: ''

stages:
  - stage: Build
    displayName: Building
    dependsOn: []
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: BuildARM
        displayName: ARM & Verify
        steps:
          - bash: az bicep build -f deploy/azuredeploy.bicep --outdir /tmp
            displayName: Compile Bicep
          - bash: |
              cmp --silent /tmp/azuredeploy.json deploy/azuredeploy.json
              if [ $? -ne  0 ]; then
                echo '🚨 Compiled ARM json does not match'
                echo '⚠️ Compile the bicep into ARM and commit to pass'
                exit 1
              fi
            displayName: Verify built bicep matches ARM in repo

      - job: BuildGoogleFitOnFhir
        displayName: Project
        steps:
          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk'
            inputs:
              useGlobalJson: true
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: build
              projects: '**/*.csproj'
