parameters:
  environment: ''

stages:
  - stage: Build
    displayName: Building
    dependsOn: []
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: BuildARM
        displayName: ARM & Verify
        steps:
          - bash: az bicep build -f deploy/azuredeploy.bicep --outdir /tmp
            displayName: Compile Bicep
          - bash: |
              cmp --silent /tmp/azuredeploy.json deploy/azuredeploy.json
              if [ $? -ne  0 ]; then
                echo 'ðŸš¨ Compiled ARM json does not match'
                echo 'âš ï¸ Compile the bicep into ARM and commit to pass'
                exit 1
              fi
            displayName: Verify built bicep matches ARM in repo

      - job: BuildGoogleFitOnFhir
        displayName: Project
        steps:
          - task: DotNetCoreCLI@2
            displayName: Build
            inputs:
              command: publish
              publishWebProjects: false
              projects: '**/*.csproj'
              zipAfterPublish: true
              arguments: >
                --configuration Release
                --output $(Build.ArtifactStagingDirectory)

          - publish: $(Build.ArtifactStagingDirectory)
            artifact: dotnet-release
            displayName: Publish staged artifacts
