parameters:
  environment: ''

stages:
  - stage: Clean
    displayName: Cleaning
    dependsOn: [Deploy]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: DestroyResources
        displayName: Cleanup Reesources
        steps:
          - bash: echo "🧨"
            displayName: Destroy <resource-group>