parameters:
  - name: environment
    default: ''

stages:
  - stage: EphemeralDeploy
    displayName: Deploying Ephemeral
    dependsOn: [Build]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: DeployResources
        displayName: Resources
        steps:
          - download: current
            artifact: dotnet-release
            displayName: Download dotnet-release artifact
          - task: AzureCLI@2
            displayName: Deploy $(basename)
            inputs:
              azureSubscription: ${{ variables.azure_service_connection_name }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) --name $(basename)
          - template: ../steps/deploy-parse-arm.yml
            parameters:
              displayName: Deploy resources for $(basename)
              azureSubscription: ${{ variables.azure_service_connection_name }}
              resourceGroupName: $(basename)
              location: $(location)
              overrideParameters: >
                -basename "$(basename)"
              armFile: ./deploy/azuredeploy.json
          - template: ../steps/deploy-source-to-functionapp.yml
            parameters:
              azureSubscription: ${{ variables.azure_service_connection_name }}
              resourceGroupName: $(basename)
              appName: GoogleFitOnFhir.Identity
              resourceName: $(identityAppName)
              releasesDir: $(Pipeline.Workspace)/dotnet-release
          - template: ../steps/deploy-source-to-functionapp.yml
            parameters:
              azureSubscription: ${{ variables.azure_service_connection_name }}
              resourceGroupName: $(basename)
              appName: GoogleFitOnFhir.SyncEvent
              resourceName: $(syncEventAppName)
              releasesDir: $(Pipeline.Workspace)/dotnet-release
          - template: ../steps/deploy-source-to-functionapp.yml
            parameters:
              azureSubscription: ${{ variables.azure_service_connection_name }}
              resourceGroupName: $(basename)
              appName: GoogleFitOnFhir.PublishData
              resourceName: $(publishDataAppName)
              releasesDir: $(Pipeline.Workspace)/dotnet-release
      - job: Debug
        displayName: Debug
        dependsOn: [DeployResources]
        variables:
          test: $[ dependencies.DeployResources.outputs['outputVars.userKeyVaultName'] ]
        steps:
          - bash: |
              echo "$(test)"
            displayName: "Echo output"
