parameters:
  environment: ''

stages:
  - stage: Deploy
    displayName: Deploying
    dependsOn: [Build]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: DeployResourceGroup
        displayName: Deploy Resource Group
        steps:
          - task: AzureCLI@2
            displayName: Deploy $(basename)
            inputs:
              azureSubscription: ${{ variables.azure_service_connection_name }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) --name $(basename)
          - template: ../steps/deploy-parse-arm.yml
            parameters:
              displayName: Deploy resources for $(basename)
              azureSubscription: ${{ variables.azure_service_connection_name }}
              resourceGroupName: $(basename)
              location: $(location)
              overrideParameters: >
                -basename "$(basename)"
              armFile: ./deploy/azuredeploy.json
