parameters:
  - name: environment
    default: ''

stages:
  - stage: DurableDeploy
    displayName: Deploying Durable
    dependsOn: [EphemeralDeploy]
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
      - name: durable-basename
        value: gfit2fhirdurable
    jobs:
      - job: DeployResources
        displayName: Resources
        steps:
          - task: AzureCLI@2
            displayName: Deploy $(durable-basename)
            inputs:
              azureSubscription: ${{ variables.azure_service_connection_name }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az group create --location $(location) \
                  --name $(durable-basename)
          - template: ../steps/deploy-parse-arm.yml
            parameters:
              displayName: Deploy resources for $(durable-basename)
              azureSubscription: ${{ variables.azure_service_connection_name }}
              resourceGroupName: $(durable-basename)
              location: $(location)
              overrideParameters: >
                -basename "$(durable-basename)"
              armFile: ./deploy/e2e-durable/azuredeploy.json
          - task: AzureCLI@2
            displayName: Copy refresh token to ephemeral keyvault
            inputs:
              azureSubscription: ${{ variables.azure_service_connection_name }}
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                TOKEN=$(az keyvault secret show \
                  --vault-name $(durable-basename)-kv \
                  --name gfit-refresh-token | jq .value -r)
                az keyvault secret set \
                  --vault-name $(infraKeyVaultName) \
                  --name $(test_user) \
                  --value $TOKEN
