parameters:
  - name: environment
    default: ''

stages:
  - stage: E2ETests
    displayName: E2ETests
    dependsOn:
    - EphemeralDeploy
    - DurableDeploy
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: AuthToGFit
        displayName: Auth to Google Fit
        steps:
          - task: Bash@3
            displayName: Get Refresh Token
            inputs:
              targetType: inlineScript
              script: |
                echo "Placeholder - Retrieve the refresh token from key vault"
                echo "TODO: Get rid of this step - previous stage already sets variable"
          - task: Bash@3
            displayName: Get Access Token
            env:
              GFIT_REFRESH_TOKEN: $(GFIT_REFRESH_TOKEN)
              GFIT_CLIENT_ID: $(GFIT_CLIENT_ID)
              GFIT_CLIENT_SECRET: $(GFIT_CLIENT_SECRET)
            inputs:
              targetType: inlineScript
              script: |
                echo "Attempting to retrieve access token using refresh token"
                FORM_DATA="grant_type=refresh_token"
                FORM_DATA+="&refresh_token=$GFIT_REFRESH_TOKEN"
                FORM_DATA+="&client_id=$GFIT_CLIENT_ID"
                FORM_DATA+="&client_secret=$GFIT_CLIENT_SECRET"
                GFIT_ACCESS_TOKEN=$(curl -X POST https://oauth2.googleapis.com/token \
                 -H "Content-type: application/x-www-form-urlencoded" -d "$FORM_DATA" \
                 | jq -r '.access_token')
      - job: SeedData
        displayName: Create New DataSource in GFit
        steps:
          - task: Bash@3
            displayName: Create DataSource for Test User
            inputs:
              targetType: inlineScript
              script: |
                echo "Placeholder - Create a new DataSource for GFit test user"
      - job: InitialDataMigration
        displayName: Initial Data Migration - For New User
        steps:
          - task: Bash@3
            displayName: PlaceholderTest1
            inputs:
              targetType: inlineScript
              script: |
                echo "Placeholder"
      - job: NewDataMigration
        displayName: New Data Migration - Since Last Sync
        steps:
          - task: Bash@3
            displayName: PlaceholderTest2
            inputs:
              targetType: inlineScript
              script: |
                echo "Placeholder"
      - job: E2ECleanup
        displayName: E2E Cleanup
        steps:
          - task: Bash@3
            displayName: Delete Datasource for Test User
            inputs:
              targetType: inlineScript
              script: |
                echo "Placeholder - Delete DataSource for GFit test user"
          - task: Bash@3
            displayName: Move Updated Refresh Token to Durable KV
            inputs:
              targetType: inlineScript
              script: |
                echo "Placeholder - Move updated refresh token from PublishData " \
                  + "back to durable key vault"                


