parameters:
  environment: ''

stages:
  - stage: Lint
    displayName: Linting
    dependsOn: []
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: LintMarkdown
        displayName: Markdown
        steps:
          - bash: npx markdownlint-cli .
            displayName: Lint the Markdown

      - job: LintYAML
        displayName: YAML
        steps:
          - bash: yamllint .
            displayName: Lint the YAML

      - job: LintFunctions
        displayName: Functions
        steps:
          - task: DotNetCoreCLI@2
            displayName: Install dotnet format
            inputs:
              command: custom
              custom: tool
              arguments: dotnet tool install -g dotnet-format
          - task: DotNetCoreCLI@2
            displayName: Check the Functions
            inputs:
              command: custom
              custom: tool
              arguments: dotnet format GoogleFitOnFhir.sln --check
