parameters:
  environment: ''

stages:
  - stage: Lint
    displayName: Linting
    dependsOn: []
    variables:
      - template: ../variables/${{ parameters.environment }}.yml
    jobs:
      - job: LintMarkdown
        displayName: Markdown
        steps:
          - bash: npx markdownlint-cli .
            displayName: Lint the Markdown

      - job: LintYAML
        displayName: YAML
        steps:
          - bash: yamllint .
            displayName: Lint the YAML
