stages:
  - stage: Package
    displayName: Publishing Nugets
    dependsOn: [Build]
    jobs:
      - job: Package
        displayName: Publishing Nugets
        steps:
          - task: NuGetAuthenticate@1

          - task: UseDotNet@2
            displayName: 'Use .NET Core sdk 7.0.x'
            inputs:
              version: 7.0.x

          - task: DotNetCoreCLI@2
            displayName: 'dotnet pack nugets'
            inputs:
              command: pack
              configuration: '$(buildConfiguration)'
              packagesToPack: '**/*.GoogleFit.csproj;**/*.Common.csproj'
              packDirectory: '$(build.artifactStagingDirectory)/nupkgs'
              versioningScheme: 'byEnvVar'
              versionEnvVar: 'nuget_version'
              zipAfterPublish: true
              nugetConfigPath: nuget.config
            env:
              nuget_version: 1.0.0-$(build.buildNumber)

          - task: PublishBuildArtifacts@1
            displayName: 'publish nuget artifacts'
            inputs:
              pathtoPublish: '$(build.artifactStagingDirectory)/nupkgs'
              artifactName: 'nuget'
              publishLocation: 'container'

          - task: NuGetCommand@2
            displayName: 'Push NuGets'
            inputs:
              command: push
              packagesToPush: '$(Build.ArtifactStagingDirectory)/nupkgs/*.nupkg'
              publishVstsFeed: 'InternalBuilds'
              allowPackageConflicts: true
              