trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  environment: ci

stages:
  - template: ./templates/stages/linting.yml
    parameters:
      environment: ${{ variables.environment }}
