trigger: none

pool:
  vmImage: windows-latest

variables:
  environment: ci

stages:
  - template: ./templates/stages/lint.yml
    parameters:
      environment: ${{ variables.environment }}

  - template: ./templates/stages/build.yml
    parameters:
      environment: ${{ variables.environment }}

  - template: ./templates/stages/analyze.yml
    parameters:
      environment: ${{ variables.environment }}

  - template: ./templates/stages/package.yml
    parameters:
      environment: ${{ variables.environment }}
